[2024-11-23T01:28:58.077+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-23T01:28:58.099+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.ingest_usa_spending_data_task scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:28:58.116+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.ingest_usa_spending_data_task scheduled__2024-11-22T00:00:00+00:00 [queued]>
[2024-11-23T01:28:58.117+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-23T01:28:58.138+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ingest_usa_spending_data_task> on 2024-11-22 00:00:00+00:00
[2024-11-23T01:28:58.156+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=80993) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-23T01:28:58.155+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'ingest_usa_spending_data_task', 'scheduled__2024-11-22T00:00:00+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpxyzuj7cm']
[2024-11-23T01:28:58.158+0000] {standard_task_runner.py:72} INFO - Started process 81001 to run task
[2024-11-23T01:28:58.158+0000] {standard_task_runner.py:105} INFO - Job 184: Subtask ingest_usa_spending_data_task
[2024-11-23T01:28:58.230+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.ingest_usa_spending_data_task scheduled__2024-11-22T00:00:00+00:00 [running]> on host 7da4b16cbed4
[2024-11-23T01:28:58.358+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='ingest_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T00:00:00+00:00'
[2024-11-23T01:28:58.362+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-23T01:28:59.061+0000] {logging_mixin.py:190} INFO - Ingesting data into federalawards
[2024-11-23T01:29:20.136+0000] {logging_mixin.py:190} INFO - Error: connection to server at "database-1.cfwk0mcqm9mf.us-east-2.rds.amazonaws.com" (18.218.251.218), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
[2024-11-23T01:29:20.137+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-23T01:29:20.151+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-23T01:29:20.153+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=ETL_usa_spending, task_id=ingest_usa_spending_data_task, run_id=scheduled__2024-11-22T00:00:00+00:00, execution_date=20241122T000000, start_date=20241123T012858, end_date=20241123T012920
[2024-11-23T01:29:20.446+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-23T01:29:20.465+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-23T01:29:20.468+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
