[2024-11-11T08:47:22.524+0000] {processor.py:186} INFO - Started process (PID=697) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:22.525+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:47:22.527+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:47:22.527+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:22.588+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:47:22.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:47:22.595+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:22.625+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.109 seconds
[2024-11-11T08:47:52.850+0000] {processor.py:186} INFO - Started process (PID=712) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:52.852+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:47:52.854+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:47:52.853+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:52.889+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:47:52.878+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:47:52.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:47:52.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.078 seconds
[2024-11-11T08:48:23.974+0000] {processor.py:186} INFO - Started process (PID=728) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:23.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:48:23.978+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:48:23.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:24.021+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:48:24.009+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:48:24.028+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:24.055+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.093 seconds
[2024-11-11T08:48:55.235+0000] {processor.py:186} INFO - Started process (PID=745) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:55.237+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:48:55.239+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:48:55.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:55.286+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:48:55.275+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:48:55.292+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:48:55.320+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.095 seconds
[2024-11-11T08:49:27.270+0000] {processor.py:186} INFO - Started process (PID=762) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:27.271+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:49:27.273+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:49:27.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:27.308+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:49:27.299+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:49:27.315+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:27.339+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.078 seconds
[2024-11-11T08:49:59.365+0000] {processor.py:186} INFO - Started process (PID=779) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:59.367+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:49:59.369+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:49:59.368+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:59.422+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:49:59.408+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:49:59.430+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:49:59.456+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.102 seconds
[2024-11-11T08:50:30.687+0000] {processor.py:186} INFO - Started process (PID=796) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:50:30.689+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:50:30.691+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:50:30.690+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:50:30.727+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:50:30.716+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:50:30.733+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:50:30.761+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.081 seconds
[2024-11-11T08:51:02.851+0000] {processor.py:186} INFO - Started process (PID=813) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:02.853+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:51:02.858+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:51:02.856+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:02.923+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:51:02.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:51:02.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:02.973+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.134 seconds
[2024-11-11T08:51:34.172+0000] {processor.py:186} INFO - Started process (PID=827) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:34.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:51:34.176+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:51:34.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:34.218+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:51:34.207+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:51:34.226+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:51:34.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.092 seconds
[2024-11-11T08:52:06.505+0000] {processor.py:186} INFO - Started process (PID=847) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:06.507+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:52:06.510+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:52:06.509+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:06.561+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:52:06.547+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:52:06.571+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:06.603+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.107 seconds
[2024-11-11T08:52:38.001+0000] {processor.py:186} INFO - Started process (PID=864) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:38.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:52:38.006+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:52:38.005+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:38.055+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:52:38.040+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:52:38.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:52:38.096+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.107 seconds
[2024-11-11T08:53:10.161+0000] {processor.py:186} INFO - Started process (PID=881) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:10.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:53:10.170+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:53:10.169+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:10.236+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:53:10.220+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:53:10.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:10.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.137 seconds
[2024-11-11T08:53:41.511+0000] {processor.py:186} INFO - Started process (PID=895) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:41.513+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:53:41.515+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:53:41.514+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:41.561+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:53:41.548+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:53:41.568+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:53:41.601+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.102 seconds
[2024-11-11T08:54:13.668+0000] {processor.py:186} INFO - Started process (PID=915) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:13.670+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:54:13.672+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:54:13.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:13.718+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:54:13.706+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:54:13.726+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:13.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.097 seconds
[2024-11-11T08:54:45.865+0000] {processor.py:186} INFO - Started process (PID=932) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:45.867+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:54:45.869+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:54:45.869+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:45.914+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:54:45.901+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:54:45.922+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:54:45.957+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.101 seconds
[2024-11-11T08:55:17.142+0000] {processor.py:186} INFO - Started process (PID=946) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:17.144+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:55:17.147+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:55:17.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:17.197+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:55:17.184+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/financial_reports_extraction_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/financial_reports_extraction_dag.py", line 11, in <module>
    'retry_delay': timedelta(minutes=0),
                   ^^^^^^^^^
NameError: name 'timedelta' is not defined
[2024-11-11T08:55:17.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:17.241+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.110 seconds
[2024-11-11T08:55:34.550+0000] {processor.py:186} INFO - Started process (PID=963) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:34.553+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:55:34.557+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:55:34.556+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:34.590+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:55:34.589+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/financial_reports_extraction_dag.py assumed to contain no DAGs. Skipping.
[2024-11-11T08:55:34.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:55:34.632+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.098 seconds
[2024-11-11T08:56:04.914+0000] {processor.py:186} INFO - Started process (PID=992) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:04.915+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:56:04.917+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:56:04.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:04.928+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:56:04.928+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/financial_reports_extraction_dag.py assumed to contain no DAGs. Skipping.
[2024-11-11T08:56:04.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:04.947+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.042 seconds
[2024-11-11T08:56:35.115+0000] {processor.py:186} INFO - Started process (PID=1007) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:35.116+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:56:35.118+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:56:35.118+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:35.131+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:56:35.130+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/financial_reports_extraction_dag.py assumed to contain no DAGs. Skipping.
[2024-11-11T08:56:35.132+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:56:35.151+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.045 seconds
[2024-11-11T08:57:05.500+0000] {processor.py:186} INFO - Started process (PID=1017) to work on /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:57:05.502+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/financial_reports_extraction_dag.py for tasks to queue
[2024-11-11T08:57:05.506+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:57:05.505+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:57:05.529+0000] {logging_mixin.py:190} INFO - [2024-11-11T08:57:05.529+0000] {dagbag.py:366} INFO - File /opt/airflow/dags/financial_reports_extraction_dag.py assumed to contain no DAGs. Skipping.
[2024-11-11T08:57:05.531+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/financial_reports_extraction_dag.py
[2024-11-11T08:57:05.567+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/financial_reports_extraction_dag.py took 0.094 seconds
