[2024-11-11T20:30:20.646+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-11T20:30:20.669+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:30:16.799448+00:00 [queued]>
[2024-11-11T20:30:20.681+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:30:16.799448+00:00 [queued]>
[2024-11-11T20:30:20.682+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-11T20:30:20.701+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_performance_reports_task> on 2024-11-11 20:30:16.799448+00:00
[2024-11-11T20:30:20.713+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1843) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-11T20:30:20.712+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'process_performance_reports', 'process_performance_reports_task', 'manual__2024-11-11T20:30:16.799448+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmp3wp8if1e']
[2024-11-11T20:30:20.714+0000] {standard_task_runner.py:72} INFO - Started process 1851 to run task
[2024-11-11T20:30:20.715+0000] {standard_task_runner.py:105} INFO - Job 26: Subtask process_performance_reports_task
[2024-11-11T20:30:20.778+0000] {task_command.py:467} INFO - Running <TaskInstance: process_performance_reports.process_performance_reports_task manual__2024-11-11T20:30:16.799448+00:00 [running]> on host ecd316daaa34
[2024-11-11T20:30:20.896+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='process_performance_reports' AIRFLOW_CTX_TASK_ID='process_performance_reports_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-11T20:30:16.799448+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-11T20:30:16.799448+00:00'
[2024-11-11T20:30:20.898+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-11T20:30:21.152+0000] {logging_mixin.py:190} INFO - Processing file: source-5_page-11.pdf
[2024-11-11T20:30:31.887+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:123 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:30:31.890+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:124 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:30:31.892+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/scripts/quarterly_performance_reports_extraction_script.py:125 FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
[2024-11-11T20:30:37.002+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/quarterly_performance_reports/performance_reports.csv
[2024-11-11T20:30:37.205+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/quarterly_performance_reports/amount_description.csv
[2024-11-11T20:30:37.428+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/quarterly_performance_reports/activity.csv
[2024-11-11T20:30:37.611+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 366, in process_performance_reports
    move_file_in_s3(source_bucket_name, source_file_path, source_bucket_name, f"{processed_folder}/{source_file_name}")
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 292, in move_file_in_s3
    s3.copy_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
[2024-11-11T20:30:37.632+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=process_performance_reports, task_id=process_performance_reports_task, run_id=manual__2024-11-11T20:30:16.799448+00:00, execution_date=20241111T203016, start_date=20241111T203020, end_date=20241111T203037
[2024-11-11T20:30:37.648+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-11T20:30:37.649+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 26 for task process_performance_reports_task (An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.; 1851)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 366, in process_performance_reports
    move_file_in_s3(source_bucket_name, source_file_path, source_bucket_name, f"{processed_folder}/{source_file_name}")
  File "/opt/airflow/dags/scripts/quarterly_performance_reports_extraction_script.py", line 292, in move_file_in_s3
    s3.copy_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
[2024-11-11T20:30:37.678+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-11T20:30:37.694+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-11T20:30:37.697+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
