[2024-11-21T05:59:38.541+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-21T05:59:38.565+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-21T05:59:26.838790+00:00 [queued]>
[2024-11-21T05:59:38.579+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-21T05:59:26.838790+00:00 [queued]>
[2024-11-21T05:59:38.580+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-21T05:59:38.607+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_usa_spending_data_task> on 2024-11-21 05:59:26.838790+00:00
[2024-11-21T05:59:38.645+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=59672) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-21T05:59:38.648+0000] {standard_task_runner.py:72} INFO - Started process 59683 to run task
[2024-11-21T05:59:38.645+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'process_usa_spending_data_task', 'manual__2024-11-21T05:59:26.838790+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmp04a9asyj']
[2024-11-21T05:59:38.649+0000] {standard_task_runner.py:105} INFO - Job 154: Subtask process_usa_spending_data_task
[2024-11-21T05:59:38.735+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-21T05:59:26.838790+00:00 [running]> on host 7da4b16cbed4
[2024-11-21T05:59:38.872+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='process_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-21T05:59:26.838790+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-21T05:59:26.838790+00:00'
[2024-11-21T05:59:38.876+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-21T05:59:39.313+0000] {logging_mixin.py:190} INFO - Processing file: df_spending_by_award_11_17_2024.csv
[2024-11-21T05:59:39.748+0000] {logging_mixin.py:190} INFO - Processing file: federal_account_funding_df_2024-11-17.csv
[2024-11-21T05:59:42.544+0000] {logging_mixin.py:190} INFO - Processing file: other_variables_11_17_2024.csv
[2024-11-21T05:59:42.867+0000] {logging_mixin.py:190} INFO - Processing file: sub_award_df_2024-11-17.csv
[2024-11-21T05:59:43.266+0000] {logging_mixin.py:190} INFO - Processing file: transactions_df_2024-11-17.csv
[2024-11-21T06:00:04.535+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/states_20241121_060004.csv
[2024-11-21T06:00:04.753+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/cfda_20241121_060004.csv
[2024-11-21T06:00:04.997+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/agency_20241121_060004.csv
[2024-11-21T06:00:05.253+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/sub_agency_20241121_060004.csv
[2024-11-21T06:00:05.668+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/recipients_20241121_060004.csv
[2024-11-21T06:00:06.310+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/grants_20241121_060004.csv
[2024-11-21T06:00:06.761+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/federal_awards_20241121_060004.csv
[2024-11-21T06:00:08.039+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/funding_20241121_060004.csv
[2024-11-21T06:00:08.600+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/transactions_20241121_060004.csv
[2024-11-21T06:00:09.149+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/sub_awards_20241121_060004.csv
[2024-11-21T06:00:09.372+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 524, in process_usa_spending_data
    archive_files_in_s3(s3, response, source_bucket_name, raw_archived_folder)
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 446, in archive_files_in_s3
    move_file_in_s3(
  File "/opt/airflow/dags/helpers/aws_utils.py", line 29, in move_file_in_s3
    s3.copy_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
[2024-11-21T06:00:09.434+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_usa_spending, task_id=process_usa_spending_data_task, run_id=manual__2024-11-21T05:59:26.838790+00:00, execution_date=20241121T055926, start_date=20241121T055938, end_date=20241121T060009
[2024-11-21T06:00:09.478+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-21T06:00:09.480+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 154 for task process_usa_spending_data_task (An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.; 59683)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 524, in process_usa_spending_data
    archive_files_in_s3(s3, response, source_bucket_name, raw_archived_folder)
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 446, in archive_files_in_s3
    move_file_in_s3(
  File "/opt/airflow/dags/helpers/aws_utils.py", line 29, in move_file_in_s3
    s3.copy_object(
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 569, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/client.py", line 1023, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.
[2024-11-21T06:00:09.537+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-21T06:00:09.574+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-21T06:00:09.578+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
