[2024-11-20T06:21:12.344+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T06:21:12.370+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-20T06:21:10.152098+00:00 [queued]>
[2024-11-20T06:21:12.382+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-20T06:21:10.152098+00:00 [queued]>
[2024-11-20T06:21:12.382+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2024-11-20T06:21:12.398+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_usa_spending_data_task> on 2024-11-20 06:21:10.152098+00:00
[2024-11-20T06:21:12.408+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=44897) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-20T06:21:12.409+0000] {standard_task_runner.py:72} INFO - Started process 44899 to run task
[2024-11-20T06:21:12.409+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'ETL_usa_spending', 'process_usa_spending_data_task', 'manual__2024-11-20T06:21:10.152098+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/project_dag.py', '--cfg-path', '/tmp/tmpey65_esr']
[2024-11-20T06:21:12.412+0000] {standard_task_runner.py:105} INFO - Job 149: Subtask process_usa_spending_data_task
[2024-11-20T06:21:12.466+0000] {task_command.py:467} INFO - Running <TaskInstance: ETL_usa_spending.process_usa_spending_data_task manual__2024-11-20T06:21:10.152098+00:00 [running]> on host 7da4b16cbed4
[2024-11-20T06:21:12.573+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ETL_usa_spending' AIRFLOW_CTX_TASK_ID='process_usa_spending_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T06:21:10.152098+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T06:21:10.152098+00:00'
[2024-11-20T06:21:12.574+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T06:21:12.816+0000] {logging_mixin.py:190} INFO - Processing file: df_spending_by_award_11_17_2024.csv
[2024-11-20T06:21:13.206+0000] {logging_mixin.py:190} INFO - Processing file: federal_account_funding_df_2024-11-17.csv
[2024-11-20T06:21:14.102+0000] {logging_mixin.py:190} INFO - Processing file: other_variables_11_17_2024.csv
[2024-11-20T06:21:14.435+0000] {logging_mixin.py:190} INFO - Processing file: sub_award_df_2024-11-17.csv
[2024-11-20T06:21:14.722+0000] {logging_mixin.py:190} INFO - Processing file: transactions_df_2024-11-17.csv
[2024-11-20T06:21:16.915+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/states_20241120_062116.csv
[2024-11-20T06:21:17.133+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/cfda_20241120_062116.csv
[2024-11-20T06:21:17.401+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/agency_20241120_062116.csv
[2024-11-20T06:21:17.605+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/sub_agency_20241120_062116.csv
[2024-11-20T06:21:17.826+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/recipients_20241120_062116.csv
[2024-11-20T06:21:18.244+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/grants_20241120_062116.csv
[2024-11-20T06:21:18.648+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/federal_awards_20241120_062116.csv
[2024-11-20T06:21:19.275+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/funding_20241120_062116.csv
[2024-11-20T06:21:19.667+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/transactions_20241120_062116.csv
[2024-11-20T06:21:20.025+0000] {logging_mixin.py:190} INFO - File saved to S3: s3://project-processed-data/usa_spending_data/sub_awards_20241120_062116.csv
[2024-11-20T06:21:20.032+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 537, in process_usa_spending_data
    move_file_in_s3(
    ^^^^^^^^^^^^^^^
NameError: name 'move_file_in_s3' is not defined
[2024-11-20T06:21:20.122+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=ETL_usa_spending, task_id=process_usa_spending_data_task, run_id=manual__2024-11-20T06:21:10.152098+00:00, execution_date=20241120T062110, start_date=20241120T062112, end_date=20241120T062120
[2024-11-20T06:21:20.172+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T06:21:20.174+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 149 for task process_usa_spending_data_task (name 'move_file_in_s3' is not defined; 44899)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_extraction/usa_spending_extraction_script.py", line 537, in process_usa_spending_data
    move_file_in_s3(
    ^^^^^^^^^^^^^^^
NameError: name 'move_file_in_s3' is not defined
[2024-11-20T06:21:20.257+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T06:21:20.276+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T06:21:20.281+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
